/**
 * UI_COPY — textes d'interface fonctionnels (charte §19).
 * Simples, sans slogan, sans règle interne transformée en accroche.
 * Les variantes humoristiques vivent dans humor.ts et disparaissent en mode sobre.
 */
export const SITE = {
  name: 'Ça vote ?',
  domain: 'çavote.fr',
  description:
    'Un test pour voir quels candidats à la présidentielle 2027 sont proches de tes réponses, avec les sources et les limites. Et un fil d’actu politique qui ne se prend pas au sérieux, sauf sur les faits.',
}

/** Mention éditoriale publique, voulue par la rédaction */
export const AI_NOTICE =
  'Ça vote ? est alimenté par l’IA, avec le moins d’intervention humaine possible, pour limiter le risque d’influence humaine. Les mêmes règles s’appliquent à tous les candidats, et chaque information renvoie à sa source publique : programmes, déclarations, documents officiels, presse.'

export const UI_COPY = {
  nav: {
    home: 'Accueil',
    test: 'Le test',
    radar: 'Radar',
    actors: 'Candidats',
    quiz: 'Quiz',
    urne: 'L’urne',
    studio: 'Studio',
    more: 'Plus',
    profile: 'Mon profil',
    method: 'Méthode',
    shop: 'Boutique',
  },
  home: {
    title: 'Qu’est-ce qui compte pour toi ?',
    lede: '42 questions sur ce que tu veux pour le pays. Ensuite, on regarde qui propose quoi, avec les sources. Tes réponses restent sur ton téléphone.',
    cta: 'Faire le test',
    ctaSecondary: 'Lire le fil d’actu',
    duration: 'Environ 10 minutes. Tu peux passer les questions.',
  },
  test: {
    start: 'Commencer',
    next: 'Suivante',
    back: 'Précédente',
    skip: 'Je préfère passer',
    dontKnow: 'Je ne sais pas',
    depends: 'Cela dépend',
    dependsHint: 'Si tu veux, précise de quoi (reste sur ton appareil) :',
    scale: ['Tout à fait opposé', 'Plutôt opposé', 'Position intermédiaire', 'Plutôt favorable', 'Tout à fait favorable'] as const,
    chapterDone: 'Chapitre terminé',
    continue: 'Continuer',
    prioritiesTitle: 'Qu’est-ce qui pèse le plus pour toi ?',
    prioritiesLede: 'Répartis 10 jetons entre les sept thèmes. Tu peux aussi garder une répartition égale.',
    redLine: 'Ligne rouge',
    redLineOn: 'Ligne rouge posée',
    redLineHint: 'Un désaccord sur ce point compterait vraiment pour toi. Il sera signalé à part dans les résultats, sans changer les scores.',
    scaleAgainst: 'Contre',
    scaleFor: 'Pour',
    tokensLeft: (n: number) => (n === 0 ? 'Tous tes jetons sont posés' : `${n} jeton${n > 1 ? 's' : ''} à poser`),
    tokensHelp: 'Touche un thème pour y poser un jeton, ou fais glisser un jeton dessus. Touche « − » pour le reprendre.',
    tokensEqual: 'Garder une répartition égale',
    tokensReset: 'Reprendre tous les jetons',
    seeResults: 'Voir mes résultats',
  },
  storage: {
    title: 'Où vont tes réponses ?',
    body: 'Nulle part. Le calcul se fait dans ton navigateur. Rien n’est envoyé à nos serveurs ni à une IA.',
    session: 'Ne rien garder après fermeture',
    sessionHint: 'Tout s’efface quand tu fermes l’onglet.',
    local: 'Garder sur cet appareil',
    localHint: 'Pour reprendre plus tard et voir ce qui change pendant la campagne. Si l’appareil est partagé, préfère l’autre option. Vider les données du navigateur efface aussi ton profil.',
  },
  results: {
    title: 'Voilà ce qui ressort de tes réponses.',
    scoreLabel: 'Proximité sur les sujets documentés',
    notComparable: 'Pas de podium pour l’instant.',
    notComparableWhy: 'Pour départager honnêtement les candidats, il faut connaître leur position sur les mêmes questions. Ce n’est pas encore le cas : on n’invente pas un classement.',
    notComparableDetail: 'Le détail',
    alphabetical: 'En attendant, voici ta proximité avec chacun, sur ce qu’on sait de lui. Ordre alphabétique, pas de préférence.',
    close: 'Écart de moins de 2 points : l’ordre n’est pas déterminant.',
    sensitive: 'Ordre sensible aux hypothèses : en faisant varier un peu le poids des thèmes, le classement change.',
    unknown: 'On n’a pas trouvé de position explicite sur ce point.',
    why: 'Le détail, question par question',
    cardTitle: 'Ta carte d’électeur',
    cardTraits: 'Ce qui ressort le plus de tes réponses',
    cardMatch: 'Le plus proche de tes réponses',
    cardNoMatch: 'Pas encore assez de positions communes pour désigner un candidat plus proche.',
    lean: { strong: 'Nettement', mild: 'Plutôt', middle: 'Pile entre les deux' },
    leanNote: 'Lecture : 0 à 20 « nettement », 20 à 40 « plutôt », 40 à 60 « entre les deux », puis l’inverse vers 100.',
    agreement: { proche: 'proche (0 ou 1 cran d’écart)', moyen: 'écart moyen (2 crans)', oppose: 'opposé (3 ou 4 crans)', ambigu: 'position ambiguë', inconnu: 'position inconnue' },
    closeOn: 'Proches sur',
    farOn: 'Opposés sur',
    redLines: 'Tes lignes rouges',
    redLineStatus: { desaccord: 'désaccord documenté', inconnu: 'position inconnue', ambigu: 'position ambiguë, désaccord possible', accord: 'pas de désaccord' },
    tie: 'Ex æquo',
    gaugeLegend: 'Noir : proximité sur les positions connues. Jaune : la fourchette possible tant que des positions manquent.',
  },
  quiz: {
    play: 'Faire le quiz',
    data: 'Tes réponses ne sont pas gardées : seul ton email l’est, si tu choisis de le donner.',
  },
  consent: {
    title: 'Un cookie ? Seulement pour compter.',
    body: 'Si tu acceptes, Google Analytics mesure la fréquentation du site : pages vues, durée de visite, type d’appareil, pays. Il est coupé pendant le test, sur tes résultats, ton profil et le studio : il ne voit jamais tes réponses. Si tu refuses, tout marche pareil.',
    details: 'Choix gardé 6 mois sur cet appareil, modifiable en bas de chaque page. Les données sont traitées par Google, aux États-Unis, dans le cadre du Data Privacy Framework.',
    humor: 'On ne vend rien. On veut juste savoir si quelqu’un nous lit.',
    accept: 'Accepter',
    refuse: 'Refuser',
    more: 'Détails',
    manage: 'Cookies : changer d’avis',
  },
  medias: {
    kicker: 'Observatoire des médias',
    title: 'Qui possède ton info',
    lede: 'Chaînes, radios, journaux, sites : à qui ils appartiennent, et qui a le dernier mot.',
    pending: 'Les premières fiches arrivent.',
    updated: (d: string) => `Mis à jour le ${d}`,
    figOwners: (owners: number, medias: number) => ({ num: String(owners), label: `propriétaires pour ${medias} médias` }),
    figTop: (name: string, n: number) => ({ num: String(n), label: `médias pour ${name} : le plus gros portefeuille privé` }),
    figArcom: (n: number, chans: number) => ({ num: String(n), label: `décisions de l’Arcom ou du Conseil d’État sur l’info politique, pour ${chans} chaîne${chans > 1 ? 's' : ''}` }),
    splitTitle: 'Qui a le dernier mot',
    splitHint: 'Part des médias selon qui décide en dernier ressort.',
    splitLead: (n: number, total: number, label: string) => `${n} médias sur ${total} : ${label.charAt(0).toLowerCase()}${label.slice(1)} a le dernier mot.`,
    ownersTitle: 'Qui possède quoi',
    arcomTitle: 'Rappelés à l’ordre',
    arcomHint: 'Décisions sur le pluralisme, le temps de parole ou l’honnêteté de l’information.',
    arcomCount: (n: number) => `Rappelé à l’ordre ${n} fois`,
    cardsTitle: 'Les fiches',
    controller: 'Le dernier mot',
    owners: 'Actionnaires',
    group: 'Groupe',
    alsoOwns: 'Le même propriétaire a aussi',
    extract: 'L’extrait',
    source: 'Source',
    howTo: 'Comment on établit une fiche',
    free: {
      teaser: (n: number) => `${n} médias n’ont ni milliardaire, ni grand groupe, ni l’État au-dessus d’eux.`,
      cta: 'Voir les médias libres',
      kicker: 'Observatoire des médias',
      title: 'Les médias libres',
      lede: 'Ni milliardaire, ni grand groupe, ni État au-dessus d’eux : ils appartiennent à leurs journalistes, leurs salariés, leurs lecteurs, ou à une structure sans but lucratif.',
      rule: 'Un fonds créé ou financé par un milliardaire ne compte pas : Le Monde ou Libération n’y figurent donc pas.',
      count: (n: number, total: number) => ({ num: String(n), label: `médias libres sur ${total} suivis` }),
      all: 'Tous les propriétaires',
      empty: 'Les premières fiches arrivent.',
    },
    follow: 'Être prévenu des rachats',
  },
  urne: {
    kicker: 'L’urne de Ça vote ?',
    title: 'Tu sais déjà pour qui tu votes ?',
    lede: 'Glisse ton bulletin. Un par connexion, anonyme pour de vrai : on compte les voix, on ne sait pas qui a voté quoi.',
    notPoll: 'Consultation en ligne ouverte à tous, non représentative : ce n’est pas un sondage.',
    blank: 'Vote blanc',
    pick: 'Choisis ton bulletin',
    confirm: (name: string) => `Tu glisses le bulletin « ${name} » dans l’urne ?`,
    confirmYes: 'À l’urne',
    confirmNo: 'Je change',
    dropping: 'Ton bulletin part dans l’urne…',
    noteBallot: 'ton bulletin',
    voted: 'A voté !',
    already: 'Cette connexion a déjà voté. Un bulletin par personne, même ici.',
    robot: 'Vérification anti-robots en échec. Recharge la page et réessaie.',
    tooMany: 'Trop de tentatives. Réessaie dans quelques minutes.',
    down: 'L’urne est fermée pour l’instant. Réessaie plus tard.',
    resultsTitle: 'Le dépouillement',
    resultsCount: (n: number) => `${n.toLocaleString('fr-FR')} bulletin${n > 1 ? 's' : ''}`,
    resultsEmpty: 'Urne vide pour l’instant. Le premier bulletin, c’est peut-être le tien.',
    frozen: 'Résultats masqués la veille et le jour du scrutin, comme le veut la loi.',
    share: 'Partager l’urne',
    shareText: 'Tu sais pour qui tu votes ? Glisse ton bulletin dans l’urne de Ça vote ?',
    copied: 'Lien copié',
    howTitle: 'Comment l’anonymat est garanti',
    how: [
      'Ton bulletin ajoute 1 à un compteur. Le compteur ne contient que des nombres, sans date ni identifiant.',
      'Pour empêcher les votes multiples, on garde une empreinte de ta connexion, brouillée par une clé secrète et impossible à reconvertir en adresse. Elle n’est jamais rangée avec ton choix.',
      'Ton navigateur fait un petit calcul invisible avant de voter : un humain ne le remarque pas, un robot qui vote mille fois doit le payer mille fois.',
      'Aucun lien avec le test : tes réponses restent sur ton appareil, l’urne ne les voit jamais.',
    ],
  },
  erase: 'Effacer toutes mes données',
  share: 'Préparer une image à partager',
} as const
